bookstore/urls.py
from django.urls import path
from .views import (PublisherList, PublisherDetail, 
                    BookListView, PublisherCreateView, 
                    PublisherUpdateView, PublisherDeleteView)


app_name = 'bookstore'
urlpatterns = [
    path('publisher/', PublisherList.as_view(), name='publisher'),
    path('publisher/add/', PublisherCreateView.as_view(), name='publisher-add'),
    path('publisher/<int:pk>/', PublisherDetail.as_view(), name='publisher_detail'),
    path('publisher/<int:pk>/update/', PublisherUpdateView.as_view(), name='publisher_update'),
    path('publisher/<int:pk>/delete/', PublisherDeleteView.as_view(), name='publisher_delete'),
    path('book/', BookListView.as_view(), name='book'),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('todoapp/', include('todoapp.urls')),
    path('bookstore/', include('bookstore.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
# when using class base views.
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]


# when using function base views.
# app_name = 'polls'
# urlpatterns = [
#     path('', views.index, name='index'),
#     path('<int:question_id>/', views.detail, name='detail'),
#     # ex: /polls/5/results/
#     path('<int:question_id>/results/', views.results, name='results'),
#     # ex: /polls/5/vote/
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]

bookstore/models.py
from django.db import models


class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    class Meta:
        ordering = ["-name"]
    

    def __str__(self):
        return self.name

class Author(models.Model):
    salutation = models.CharField(max_length=10)
    name = models.CharField(max_length=200)
    email = models.EmailField()
    #headshot = models.ImageField(upload_to='author_headshots')

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField('Author')
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    publication_date = models.DateField()

    def __str__(self):
        return self.title
    

bookstore/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from bookstore.models import Publisher, Book, Author


class PublisherList(ListView):
    model = Publisher
    context_object_name = 'publishers'


class PublisherDetail(DetailView):
    model = Publisher

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["books"] = Book.objects.all()
        return context


class BookListView(ListView):
    queryset = Book.objects.order_by('-publication_date')
    

class PublisherCreateView(CreateView):
    model = Publisher
    fields = ['name', 'address', 'city', 'state_province', 'country', 'website']
    success_url = '/bookstore/publisher/'


class PublisherUpdateView(UpdateView):
    model = Publisher
    fields = ['name', 'address', 'city', 'state_province', 'country', 'website']
    success_url = '/bookstore/publisher/'

class PublisherDeleteView(DeleteView):
    model = Publisher
    success_url = reverse_lazy('bookstore:publisher')

bookstore/templates/bookstore/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>{% block title_block %}
    {% endblock  %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="">Bookstore</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
  </div>
</nav>
    <div class="container">
   
   
      {% block content %}
      {% endblock  %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

bookstore/templates/bookstore/book_list.html
{% extends 'bookstore/base.html' %}

{% block titlt_block %}
bookstore
{% endblock  %}
{% block content %}
    
    <ul>
    <h1>Books in Store</h1>
        {% for book in book_list %}
            <li class="list-group-item">{{ book.title }}</li>
        {% endfor %}
    </ul>
{% endblock  %}

bookstore/templates/bookstore/home.html
{% extends 'bookstore/base.html' %}

{% block titlt_block %}
bookstore
{% endblock  %}
{% block cotent %}
 bookstore
{% endblock  %}

bookstore/templates/bookstore/publisher_confirm_delete.html
{% extends 'bookstore/base.html' %}

{% block titlt_block %}
delete pub
{% endblock  %}
{% block content %}
<h1>Do you which to delete {{ publisher.name }} publisher</h1>
<form method="POST" action=".">
{% csrf_token %}

<button type="submit" class="btn btn-danger">Delete</button>
<a href="{% url 'bookstore:publisher_detail' publisher.id %}" class="btn btn-primary">Cancel</a>
</form>
{% endblock  %}

bookstore/templates/bookstore/publisher_detail.html
{% extends 'bookstore/base.html' %}

{% block titlt_block %}
bookstore
{% endblock  %}
{% block content %}
 <h2>Publisher Detail</h2>
 <div class="jumbotron">
  <h1 class="display-3">{{ publisher.name }}</h1>
  <h4 class="display-5">Adress:</h4>
  <p class="lead ml-5 mb-0">{{ publisher.address }}</p>
  <p class="lead ml-5 mb-0">{{ publisher.city }}</p>
  <p class="lead ml-5 mb-0">{{ publisher.state_province }}</p>
  <p class="lead ml-5 mb-0">{{ publisher.country }}</p>
  <div class="float-right">
  <a href="{% url 'bookstore:publisher_delete' publisher.id %}" class="btn btn-danger">Delete</a>
  </div>
  <hr class="my-4">
  
  <h3>List of Book Published</h3>
  <ol>
    {% for book in books %} 
        <li>{{ book.title }}</li>
        {% empty %}
        <p>There is no book available</P>
    {% endfor %}
   
  </ol>
  
</div>
{% endblock  %}

bookstore/templates/bookstore/publisher_form.html
{% extends 'bookstore/base.html' %}
{% load crispy_forms_tags %}
{% block titl_block %}
piblisher form
{% endblock  %}

{% block content %}
<h1>Add Publisher</h1>
<form method="POST" action=".">
{% csrf_token %}
{{ form|crispy }}
<button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock  %}

bookstore/templates/bookstore/publisher_list.html
{% extends 'bookstore/base.html' %}

{% block titlt_block %}
bookstore
{% endblock  %}
{% block content %}
 <h2>Publisher list</h2>
    <ul class="list-group">
        {% for publisher in publishers %}
                <li class="list-group-item">
                    <a href="{% url 'bookstore:publisher_detail' publisher.pk %}">{{ publisher.name }}</a>
                </li>
            {% empty %}
            <li class="list-group-item">There is no publisher</li>
        {% endfor %}
    </ul>
 
{% endblock  %}